[build]
target = "riscv32imac-esp-espidf"

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --erase-parts otadata --bootloader ./target/riscv32imac-esp-espidf/release/bootloader.bin"
rustflags = [
    "--cfg", "espidf_time64", # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
    "-C", "force-frame-pointers=yes",
    "-C", "debuginfo=2",
    "-C", "force-unwind-tables=yes",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32c6"
ESP_IDF_VERSION = "v5.1.4"
